### ISSUE TITLE
Parameter 2 to filter_wysiwyg_fields_form_alter_alter() expected to be a reference

### ISSUE THREAD

**Issue by kattekrab** [Decipher/wysiwyg_fields#2]
installed the module then got these errors... hope this helps in tracking down the bug. :)
# warning: Parameter 2 to filter_wysiwyg_fields_form_alter_alter() expected to be a reference, value given in /var/www/includes/common.inc on line 2892.
# warning: Parameter 2 to content_wysiwyg_fields_form_alter_alter() expected to be a reference, value given in /var/www/includes/common.inc on line 2892.
# warning: Parameter 2 to wysiwyg_fields_wysiwyg_fields_form_alter_alter() expected to be a reference, value given in /var/www/includes/common.inc on line 2892.

**Comment by Decipher** [comment]
A fix has been commited for this issue.
