### ISSUE TITLE
Javascript issue

### ISSUE THREAD

**Issue by kattekrab** [Decipher/wysiwyg_fields#3]
Drupal.wysiwyg.plugins[pluginName] is undefined
[Break on this error] if (typeof Drupal.wysiwyg.plugins[pluginName].invoke == 'function') {\nckeditor-3.0.js?e (line 170)

**Comment by Decipher** [comment]
I'm fairly certain that this issue has been resolved.

If you can confirm that it would be fantastic.
To do so you will need to do the following:
- Update to latest code.
- Turn module off and on again (seriously)

Done.

**Comment by Decipher** [comment]
Marking this is fixed.
